formatter: markdown table

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  color: true
  description: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: true
  required: true

sections:
  hide:
    - modules
    - resources
    - providers
